### ISSUE TITLE
Customising replies

### ISSUE THREAD

**Issue by jugglerchris** [lumail/lumail#243]
At the moment lumail generates the default message when replying (To, subject, Message-ID, References, etc.), and allows the user to customise the Subject mangling and signature.

But there are some other things I'd like to be able to do, like:
* Add a "On <date>, <name> wrote:" type of line before the quoted body
* Change the From: header (eg if the message being replied to was sent to one of my alternate e-mail addresses, or it's sending to a mailing list and I need to use the address I subscribed from)
* Add or modify arbitrary other headers

So I would like to have a new lua callback, something like:

```lua
on_reply_transform_message(orig, reply)
```

where `orig` is the original `CMessage` we're replying to, and `reply` is the new message which can be modified by the callback.  (This relies on exposing enough methods on the Lua `CMessage` binding).  It would be called at about the same time as `on_reply_transform_subject`.

Since I need the feature I'll probably end up doing it in my fork anyway, but I'd appreciate any feedback so that I can do it in a way that's more likely to be accepted if/when I get around to trying to submit the changes upstream.  :-)

**Comment by skx** [comment]
I've thought about this and I think that what I'd prefer to see is a callback which looks like this:

   on_create_reply( msg, filename );

If it exists it will take a message, being replied to, and a file to write the text to.  If the callback doesn't exist the current behaviour will remain as-is.

Does that seem reasonable?  I think that trying to return a CMessage object would be a mistake, as would returning a string.

**Comment by jugglerchris** [comment]
Hi,
I think that makes a lot of sense!
Two further things to think about, though:
* It would be nice to not have to re-implement all the current behaviour if you only want to add one line to the body - eg generating a message-ID, references:, etc.  I think this mostly applies to the headers, but might be an issue if any MIME handling is needed.  (What about doing the same when forwarding messages including attachments?)
* I might come up with a reason for wanting to modify a message after editing as well, without having to have to handle all the message parsing and regeneration in the config.lua.  But I haven't got a concrete need/idea here at the moment, so maybe ignore this one for now!

Some ideas:
* Have the `on_create_reply` write the message body to the file, and return a Lua table of headers; lumail would then add anything missing (ie everything it would normally generate that wasn't provided by the callback - quoted body and/or default headers).
* Provide a `write_message(filename, headers, body)` function for `on_create_reply` to use for the purpose.

Chris

**Comment by skx** [comment]
Both your ideas are good, to be honest I'm really struggling to decide how best to proceed.

(I'm being much slower than I'd like at handling updates here too.  Partly because i'm moving country, but partly because I'm pleased that the client actually works well enough for me to use non-stop.  Feature creep is something i want to avoid, although I appreciate that things ilke this issue will be godo for others it just makes it more important to make the right choice.)

**Comment by trou** [comment]
This feature would be nice as It would help replying to MLs as jugglerchris mentioned.

**Comment by jugglerchris** [comment]
I'm back to looking at this, as I keep being annoyed at having to switch back to mutt every time I reply to something, and I find myself with a bit of time at my computer.  :-)

Another non-ideal thing with your `on_create_reply( msg, filename )` option is that the temp file creation would be slightly more racy (not using `mkstemp`).

Thinking again, my personal priorities (which I accept are different from yours!) are:
* Full control of the resulting message (inc headers)
* Not having to duplicate the non fiddly work lumail does like generating Message ID and Date headers.  I'm ok to do quoting in Lua, since that's very simple string manipulation (and I might want to do fancy stuff like rewrapping in future).
* Having something soon (I'm happy to update my personal lumail config if the API changes/improves in future).  :-)

Here's another idea.  Add one new callback:
```lua
-- Given a message, and the headers (as a Lua table) lumail would use for the reply
-- returns either a filename where the new message has been written, or nil (lumail will do whatever
-- it would have done without on_create_reply())
on_create_reply(msg, headers)
```
and one new primitive (maybe with a better name):
```lua
-- Just a wrapper around the current C++ function; returns the filename
populate_email_on_disk(headers, body, sig)
```

Now in `bindings_message.cc::reply()`:
```C
    // between generating headers and quoting body
    std::string filename;
    bool have_message = false;
    if (on_create_reply Lua function exists) {
        call on_create_reply(msg, headers);
        if (returned a string) {
             filename = result;
             have_message = true;
    }
    if (!have_message) {
        /* Original bbody += "> " + body[i] + "\n" loop */
        /* Original filename = populate_email_on_disk(...) */
    }

    /* Same edit/send loop as before */
```

**Comment by skx** [comment]
Your new callback, and new primitive, seem good.  I'd be happy to accept such a pull-request.

Sorry I've been busy, having recently changed countries and injured my (typing) arms!   So I've been doing stuff online, but only in small doses.

**Comment by skx** [comment]
I'm sorry for the lack of update on this issue, but work on lumail has been pretty much abandoned.  

The good news is that there is a new project, [lumail2](https://github.com/lumail/lumail2/) which is very similar to this one:

* It is still console-based.
* It still operates solely on Maildir hierarchies.
* It is still written in C++, with all the scripting support provided by Lua.

Why change?  Lots of reasons, but primarily because I wanted everything to be an object: Messages, Maildirs, etc.  The rewrite is more functional than the older-codebase, smaller, simpler, and much more flexible.

If you're still interested in Lumail please do take a look:

* https://github.com/lumail/lumail2/
