### ISSUE TITLE
Stable Version?

### ISSUE THREAD

**Issue by ode79** [lumail/lumail#300]
Hi,

Is there any plan for a stable version?

I would like to try your lumail but I don't feel I can given the message on the readme 'NOTE: lumail2 may well eat your email, corrupt your email, or otherwise cause data loss'

Thanks for your help.

**Comment by skx** [comment]
I'm kinda in the middle of overhauling the documentation, and will be updating the README.md file too in the near future.

For what it is worth I do regard the current 3.0 release as stable, I'm just a little paranoid :)

**Comment by skx** [comment]
I've updated `README.md`.  Will finish the website overhaul by the end of the week.  Still I've removed the scare-quote so this can be closed now.
