### ISSUE TITLE
"make install" didn't install global config-file (was:'warning_msg' (a nil value))

### ISSUE THREAD

**Issue by ode79** [lumail/lumail#302]
I have compiled, installed, copied the config file and edited it for my account but when I start up I get `'ERROR ~/.lumail2/lumail2.lua:91: attempt to call global 'warning_msg' (a nil value)`

I haven't used lua in my work so I don't really know what the issue is.

I have lua 5.1 and lua 5.2 installed and am running Ubuntu stable.

**Comment by ode79** [comment]
ERROR ~/.lumail2/lumail2.lua:172: attempt to call global 'sorting_method' (a nil value)

**Comment by ode79** [comment]
ERROR /home/owen/.lumail2/lumail2.lua:28: attempt to index global 'keymap' (a nil value)

**Comment by skx** [comment]
You should have copied the files thusly:

* `lumail2.lua` to `/etc/lumail2/lumail2.lua`
* `lumail2.user.lua` to `~/.lumail2/lumail2.lua`

The errors your seeing suggest that the `lumail2.user.lua` file is calling things which are NOT present in the global file.

**Comment by ode79** [comment]
Ah, OK, I did run `make install` before I posted, should it copy those files for you?

I have copied the files manually now and lumail2 starts correctly.

**Comment by skx** [comment]
No need to copy files to me, but I'm pleased it now works.

I'll need to look into why `make install` didn't do the necessary thing.  But yeah all your errors come from the assumptions that functions defined in the global-config file (rather than the per-user one) will be available and callable.

**Comment by skx** [comment]
Testing this repeatedly and `make install`, when executed by `root`, __always__ installs `/etc/lumail2/lumail2.lua`.

So I'm struggling to see how this could have failed for you.

**Comment by skx** [comment]
Closed in :

* https://github.com/lumail/lumail/pull/308
