### ISSUE TITLE
Overhaul documentation.

### ISSUE THREAD

**Issue by skx** [lumail/lumail#307]
Our `README.md` file is too long, and doesn't give a great introduction.

It needs to be reworked from start to finish - not least to make sure that we call the client `lumail` not `lumail2`.

See also the bug-report for our website:

* https://github.com/lumail/lumail.org/issues/12

**Comment by fischerling** [comment]
Have you started replacing `lumail2` with `lumail` in the code ?
I would prepare a pull request if you don't mind.

**Comment by skx** [comment]
Not yet, but I will do so in the near future.  

Renaming the binary, and changing the ~/.lumail2 stuff, is the easy part :)

**Comment by fischerling** [comment]
I made #309 to do the simple renaming. So you can focus on the harder stuff ;)

**Comment by skx** [comment]
The way I would do it would be something like:

* Update the documentation to point to the new location.
* Update the code to work with the old location __and__ the new one:
   *   `~/.lumail2/$hostname`
   *   `~/.lumail2/lumail2.lua`
   *   `~/.lumail2/config.lua`
   *   `~/.lumail/$hostname`
   *   `~/.lumail/lumail.lua`
   *   `~/.lumail/config.lua`
* Make a release.
* Make another release.
  * This time warning on-startup that the locations are absolutely going to break.
* Drop the old/legacy locations.
  * Alert if present.  With a fatal error.
* Make a third release only using new location(s).

**Comment by skx** [comment]
The last two changes helped simplify the loading of user-init functions, but I think they were a mistake.

We should simplify _properly_:

* lumail will load `/etc/lumail2/lumail2.lua`
  * If it exists, as a legacy-change.
* lumail will load `/etc/lumail/lumail.lua`
  * If it exists, as the preferred config file.

__ALL__ other configuration-loading should happen from there.  The C++ code should __not__ attempt to load the user-config.  This would have several benefits:

* It is much more explicit to the user what is being loaded.
* We can wrap the legacy config-loading with a flag, and/or show a warning if they're used.
* We can change the files more easily.

**Comment by skx** [comment]
OK this is now complete:

* Global configuration file is now `/etc/lumail/lumail.lua`
  * Which is what `make install` installs.
* We load new AND legacy config files via `global.config.lua`.
  * Legacy versions will get a warning.
  * Warning will point to [the getting-started guide](https://lumail.org/getting-started/) which documents the paths.

The config-files have been renamed as `global.config.lua` and `user.config.lua` to make it explicit what they're for.

The only thing to do now is make a release, and in the next release drop the legacy paths.

**Comment by skx** [comment]
I'm happy with the current state of the documentation now, both here and on the website.

The config-file handling has been overhauled, so time for a new release.  The next release after that can drop the legacy support, and also rename the binary.
