### ISSUE TITLE
Support for lua 5.3

### ISSUE THREAD

**Issue by daurnimator** [lumail/lumail#311]
Is lumail supported with lua 5.3? I saw #116 which indicates yes. If so please mention in docs.

**Comment by skx** [comment]
Yup, docs need work as per #307.

5.3 is expected to work, and if a failure occurs this is a bug.

**Comment by skx** [comment]
Our installation-guide also explicitly mentions Lua 5.1, 5.2, and 5.3 now:

* https://lumail.org/install/
