### ISSUE TITLE
Unused linked libraries

### ISSUE THREAD

**Issue by daurnimator** [lumail/lumail#313]
```
lumail W: Unused shared library '/usr/lib/libdl.so.2' by file ('usr/bin/lumail2')
lumail W: Unused shared library '/usr/lib/libgio-2.0.so.0' by file ('usr/bin/lumail2')
```

**Comment by skx** [comment]
I admit I'm not sure what the downside is to this, nor what should be done to resolve it.

Any comment would be most welcome.

**Comment by daurnimator** [comment]
It means you're passing `-ldl` and `-lgio-2.0` when you don't need to be.

**Comment by skx** [comment]
`-lgio-2.0` comes from:

     $ pkg-config --libs  gmime-2.6
     -lgmime-2.6 -lgio-2.0 -lgobject-2.0 -lglib-2.0 

But I could drop `-ldl`, which does come from the `Makefile`.
