### ISSUE TITLE
Completion prompts unnecessarily if only one choice.

### ISSUE THREAD

**Issue by skx** [lumail/lumail#330]
"simple" steps to reproduce this use the path-completion:

* Compose an email by pressing `c`.
* Enter a recipient.
* Enter a subject.
* Write some text, and exit the editor
* Press `a` to add an attachment
* Enter `/ho` + press `TAB`.

Expected result is that `/ho` becomes `/home/`.  Instead we are presented with a choice of a single option.

The following patch _might_ be correct, but requires a second pair of eyes:

       index 6cdcb27..2f6a6d2 100644
       --- a/global.config.lua
       +++ b/global.config.lua
       @@ -3824,6 +3824,11 @@ do
              return ""
            end
        
       +    -- Only one completion?
       +    if #completions == 1 then
       +       return completions[1]
       +    end
       +
            local choice = Screen:choose_string(completions)
            if choice ~= "" then
              -- Build the buffer to return

**Comment by skx** [comment]
@fischerling might have input here.  Also on #331.

**Comment by skx** [comment]
The other solution is to avoid the choice in the choose_string method:

       diff --git a/src/screen.cc b/src/screen.cc
       index 7f4e9d8..52602e1 100644
       --- a/src/screen.cc
       +++ b/src/screen.cc
       @@ -647,6 +647,12 @@ std::string CScreen::choose_string(std::vector<std::string> choices)
            assert(choices.size() > 0);
        
            /*
       +     * IF there is only one choice - return it
       +     */
       +    if (choices.size() == 1 )
       +        return( choices.at(0));
       +
       +    /*
             * Find longest/widest entry.
             */
            size_t max = 0;

I'd avoid that solution because it changes the options - the `choose_string()` methods actually has two goals:

* Allow a choice to be made.
* Cancel a choice.

**Comment by fischerling** [comment]
The first solution looks perfect to me.
This code was in c++ I just forgot to add it to lua.
