### ISSUE TITLE
Caching of Message:format not correct after restart

### ISSUE THREAD

**Issue by fischerling** [lumail/lumail#341]
During my experiments with general header caching and speeding up the opening of my maildirs I noticed
that after a restart all messages were formated again.

I tested this with inserting `Panel:append("hit")` into the branch which finds the string in the cache.
And opening a maildir for the first time after the program start doesn't produce cache hits.

The reason for this is that we use the format string as part of the cache key. And the format string normaly contains whitespace which is used in `CCache:load` to parse the line.

**Comment by skx** [comment]
That's a great catch!

I guess we convert " " to "_" in cache-set then ..

**Comment by skx** [comment]
Does this patch solve the problem?

[key.diff.txt](https://github.com/lumail/lumail/files/1528642/key.diff.txt)

**Comment by skx** [comment]
Second attempt - does this patch help resolve the problem?

[key.diff.txt](https://github.com/lumail/lumail/files/1528651/key.diff.txt)

**Comment by fischerling** [comment]
Yes this fixes it :)

**Comment by fischerling** [comment]
And I think the cache should save entries with empty value to disk.

Header fields can be empty and if so should although be written to disk.

The file format could be something like

```
key
value
```

This would make parsing easier and would allow arbitrary chars in the key

**Comment by skx** [comment]
> Yes this fixes it :)

Great, will commit shortly.

> And I think the cache should save entries with empty value to disk.

That I'm not sure about.  How do we tell the difference between:

* No value in the cache.
* Empty value.

But a separate bug should be made for that. You might instead want to allow setting a *table* in a cache, which would ignore that problem.   (The table having keys of header-names, and their associated values.)
