### ISSUE TITLE
Performance is something we should concentrate upon

### ISSUE THREAD

**Issue by skx** [lumail/lumail#344]
I have two pain-points these days:

* Opening a large folder takes "forever".
* Sorting large folders takes a similar time.

Opening some of the mailing-lists takes a long time, presumably as a result of the stats/reads.  Sorting is still too slow.

The header cache seems like a great solution, but hasn't helped as much as I'd hoped.  For example:

         │Sort method threads took 0 seconds with 0 messages                            │
         │Sort method threads took 55 seconds with 11964 messages                       │
         │Sort method threads took 2 seconds with 118 messages                          │
         │Changed outgoing email-address to Steve Kemp <steve@steve.fi>                 │
         │Sort method threads took 1 seconds with 367 messages                          │
         │Sort method threads took 55 seconds with 11964 messages               

That last folder is the same as the second, clearly caching isn't helping a re-open, which is puzzling.  Work should be done here.  I could _almost_ tolerate it being slow the first time if it was faster the second, but here we see it isn't.

**Comment by fischerling** [comment]
Do you notice the header cache at all ? And is is working ? Are there the caches on disk ?

Where consecutive openings of a single maildir faster without the header cache ?
-> maildir_view -> index_view -> maildir_view -> index_view of the same maildir.
Because in this scenario the messages are cached as CMessages.

Which sorting do you use for threads ?

I had some performance tracking Log calls in the code during my work maybe we
should introduce them to get rid of this sluggishness.

**Comment by skx** [comment]
> Do you notice the header cache at all ? And is is working ? Are there the caches on disk ?

I can't say I notice a speedup, but the cache-files are certainly present now and populated.  For example:

       steve@ssh ~ $ ls -lash $(find /home/steve/.lumail2/ -name 'cache' | tail -n 5)
       100K -rw-r--r-- 1 steve users  99K Dec 11 09:15 /home/steve/.lumail2/cache/hcache/Automated-attic/cache
       8.0K -rw-r--r-- 1 steve users 6.7K Dec 11 10:24 /home/steve/.lumail2/cache/hcache/Automated-dmarc/cache
        20K -rw-r--r-- 1 steve users  20K Dec 11 11:47 /home/steve/.lumail2/cache/hcache/debian-user/cache
       256K -rw-r--r-- 1 steve users 255K Dec 11 09:18 /home/steve/.lumail2/cache/hcache/people-family/cache
        20M -rw-r--r-- 1 steve users  20M Dec 11 11:48 /home/steve/.lumail2/cache/hcache/people-kirsi/cache

Opening a folder, pressing `q` to go back to the maildir-view, and then reopening the folder doesn't show a speedup. I get the moving progress-slider, as the messages are read, and it takes almost exactly the same time.  The only fast thing is:

* Open the client.
* Select a maildir
   * Look at the list of messages.
* Move back to the maildir-view by pressing `q`
* Pressing `i` to jump back to the index-view __without__ reopening it.

Sorting is :

        Config:set( "index.sort", "threads" )
        Config:set( "threads.sort", "date" );

**Comment by fischerling** [comment]
I can confirm with strace that now messages are read from disk. Only the history  and both our caches are read.

I can't believe that reading and simple parsing of two files (both caches) isn't faster than reading and complex parsing of ~ 12000 files.

How long does it take if no caches are available ?

And maybe our threading algorithm is just to slow. But It shouldn't be that bad I think it is O(n).

**Comment by fischerling** [comment]
Yes sorry I meant **Not** read from disk.

> So that's about an extra 113 seconds vs 55. Not a huge difference, but still too much!

You are right we should be better. Do you know how long mutt for example needs to open this folder ?

Sadly I am not used to profiling so you are a bit on your own with this.
But if I can help with something please let me know!

**Comment by skx** [comment]
I should be able to add a `make profile` target to the `Makefile` and have a quick look over things.

**Comment by skx** [comment]
# Profiling with `gprof` 

So adding profiling means adding `-g -pg` to both `CPPFLAGS` and `LDLIBS`.  Once that is done you'll find that the file `gmon.out` is created every time you exit `lumail`.

I loaded `lumail`, opened a couple of the larger folders, closed them, moved back and forth & etc.  Once that is done you view the report by running:

      $ gmon ./lumail2 ./gmon.out

That shows the most-called methods & etc.

# Profiling with `callgrind`

I've not yet completed this but the short version is:

            valgrind --tool=callgrind [callgrind options] your-program [program options]

Then once finished you run:

            callgrind_annotate  callgrind.out.file

# Notes

Interestingly I was doing this profiling on my home desktop, with a copy of all my maildirs - made via `rsync`, and the performance was much better. I suspect the ultimate cause of my self-reported slowdown is "remote host has slow I/O.  Anyway

Will update later in the day with the actual results of profiling.

**Comment by skx** [comment]
> Will update later in the day with the actual results of profiling.

This didn't happen, but having moved my mail-host to a new machine performance is once again good. Having better disk I/O was obviously helpful!
