### ISSUE TITLE
Attempt to call global "loadstring" (a nil value)

### ISSUE THREAD

**Issue by matthiasbeyer** [lumail/lumail#348]
I get the following error:

```
lumail2.lua:3382: attempt to call global 'loadstring' (a nil value)
```

But I assume this has something to do with the way it is packaged in nixpkgs... It looks (for me) like some lua standard libs cannot be found. Could this be the error?

If yes, I have to investigate at a packaging-level, so feel free to close this issue!

**Comment by matthiasbeyer** [comment]
This was indeed a packaging error, but _also_ an error on the side (or rather "site") of lumail:

The docs state that lumail can be used with lua 5.1, 5.2 and 5.3, but "loadstring" was deprecated with 5.2, so that the example "global" configuration file does not work with lua 5.2.

lua 5.1 works, though.

Please either update the configuration file to be compatible with all versions, or update the website accordingly.

**Comment by skx** [comment]
My intention is that the code works on 5.1, 5.2, and 5.3.  The only time I discover it doesn't is when users report bugs.

I used to build/run against 5.1, these days I run against 5.2 quite happily.  You say `loadstring` is depreciated?  I see no warnings, errors, or failures with that:
 
        steve@ssh ~ $ ldd /usr/bin/lumail2 | grep lua
        liblua5.2.so.0 => /usr/lib/x86_64-linux-gnu/liblua5.2.so.0 (0x00007f8ae3469000)

**Comment by matthiasbeyer** [comment]
Hm, funny:

```
$ lua
Lua 5.2.3  Copyright (C) 1994-2013 Lua.org, PUC-Rio
> loadstring("1 + 1")
stdin:1: attempt to call global 'loadstring' (a nil value)
stack traceback:
	stdin:1: in main chunk
	[C]: in ?
```

**Comment by skx** [comment]
Works for me here:

       deagol ~ $ lua5.2 
       Lua 5.2.3  Copyright (C) 1994-2013 Lua.org, PUC-Rio
       > loadstring( "1 + 1" )
       >
       > loadstring( "print( 'OK')" )()
       OK

**Comment by matthiasbeyer** [comment]
Are you on debian?

**Comment by skx** [comment]
I'm on Debian.

previous example was jessie.  This is stretch:

        steve@ssh ~ $ lua5.2
        Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
        > loadstring( "print ' ok '" )()
        ok

**Comment by matthiasbeyer** [comment]
Filed an issue in nixpkgs (for nixos, my distribution) as this seems to be an issue with lua, not lumail.

**Comment by jugglerchris** [comment]
Sounds to me like a difference in how Lua's built.  My guess is that Debian is turning on the LUA51_COMPAT (or something like that) flags but Nix isn't.  Neither is necessarily wrong!
