### ISSUE TITLE
Screen:get_line does not handle backspace

### ISSUE THREAD

**Issue by matthiasbeyer** [lumail/lumail#349]
I'm not sure whether this is a bug or simply a missing feature,... but `Screen:get_line` seems not to be able to handle "backspace"... so typos are basically hell to fix (retyping everything).

**Comment by skx** [comment]
For me :

* backspace works
* Ctrl-b moves backwards one space, and Ctrl-d removes a character.

You could do worse than Ctrl-a , Ctrl-k at a push .. but I'd guess this is a terminal issue?

**Comment by matthiasbeyer** [comment]
Can confirm, Ctrl-b and Ctrl-d work, also Ctrl-a and Ctrl-k do, but Backspace does not. I'm using xfce4-terminal, not sure if that helps?

**Comment by skx** [comment]
If you could try xterm, gnome-terminal, or any other local terminals you have that might pin it down to a global-problem, or a problem with xfce4-terminal at least ..

**Comment by matthiasbeyer** [comment]
`xterm` works, `st` works, `rxvt` does not but `urxvt` does.

Cannot test gnome terminal because of some weird "missing .desktop" error.

**Comment by skx** [comment]
* https://bbs.archlinux.org/viewtopic.php?id=111364 ?

**Comment by matthiasbeyer** [comment]
Fixed this issue for me.

---

For future reference:

* Go to `Preferences` -> `Compatibility`
* Set `Backspace generates` to `Control-H`.

---

Thank you very much for your support!
