### ISSUE TITLE
complete_address does not work?

### ISSUE THREAD

**Issue by matthiasbeyer** [lumail/lumail#352]
I am not 100% sure I've done everything right, but it seems that `complete_address` is not called at all.

I tested with the hack from the example configuration:

```
do
  local _complete_address = complete_address
  complete_address = function(buffer)
    -- get old completions
    local token, ret = _complete_address(buffer)
    Panel:append("Completing addresses")
    return token, ret
  end
end
```

When hitting `c` and `tab`, nothing happens.

**Comment by fischerling** [comment]
I had a fast look and I think `on_complete` is only called if there is something to complete.

So try hitting `c`, type something and then hit `tab`.

**Comment by matthiasbeyer** [comment]
Yeah, if I hit `c` and then type `mail`, I get `maildirs` and `maildir_view`, which are both clearly not form the `complete_address` function...

**Comment by fischerling** [comment]
Ok this is weird. But do you get "Completing addresses" printed in the panel ?

Have you changed your global config ?
You could change `on_complete` in your global config to print the function names it calles for further debugging.

**Comment by matthiasbeyer** [comment]
> But do you get "Completing addresses" printed in the panel ?

Nope.

> Have you changed your global config ?
You could change on_complete in your global config to print the function names it calles for further debugging.

Yeah, I get a segmentation fold with that.

**Comment by fischerling** [comment]
Did you make any changes to the completion system ?

What have you changed to print the functions ?
I meant something like this:
```diff
diff --git a/global.config.lua b/global.config.lua
index fd77154..7ca8c4a 100644
--- a/global.config.lua
+++ b/global.config.lua
@@ -3787,6 +3787,7 @@ do
     for context, _ in pairs(completion_context) do
       local func = _G["complete_"..context]
       if func then
+        Panel:append("Call complete_"..context)
         local token, options = func(line)

         table.insert(tokens, token)
```

**Comment by matthiasbeyer** [comment]
Had to do some hacky things (because distro and lua packaging), but yes, this works now. It prints "address" for the context.

I just confirmed that lumail compiled from master works. So I _guess_ this was fixed somewhere between `release-3.1..dbedd10`.

**Comment by matthiasbeyer** [comment]
After browsing a bit through the codebase I noticed that the completion system was added _after_ the 3.1 release. So maybe my lumail binary is not compatible with the completion setup from the `global.config.lua`?

**Comment by fischerling** [comment]
Yes you are right the new completion system written in lua introduced with #328 uses CScreen::choose_string which is exported in fdb65e0f8c3ebeaa980ef3f7a27597be1271f798.
So a 3.1 binary isn't compatible with the global config from current master.

**Comment by matthiasbeyer** [comment]
Okay. Packaged it locally to use the version from master (dbedd10) so I do solve this issue.

Thanks a lot for your help!

**Comment by skx** [comment]
Probably time for a new release; I'm still a little unhappy with completion, but I can't face it at the moment.

Soon :)
