### ISSUE TITLE
broken link to asciinema video

### ISSUE THREAD

**Issue by masukomi** [lumail/lumail#360]
The link on [this page](https://lumail.org/screenshots/) to asciinema results in the following message.

```
This recording has been archived

All unclaimed recordings (the ones not linked to any user account) are automatically archived 7 days after upload.
```

It would be nice to have a video giving a feel for the app before installing and configuring it.

**Comment by skx** [comment]
Thanks for the report, sorry it got neglected over the Easter weekend.

I'll try to sort this out shortly.  It might be that I have to remove it, and rely upon the static-screenshots, but that would be a shame.

**Comment by skx** [comment]
This lagged, and I've just received another report.  I'll remove it shortly.

**Comment by skx** [comment]
Replaced link with archive version:

* https://web.archive.org/web/20181021214024/https://asciinema.org/a/chdqz6tb4vt9p3ifp32g4musa
